service:
  name: serverless-url-shortener

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:GetObject
      Resource:
        - Fn::Join:
            - "/"
            - - Fn::GetAtt: [ Bucket, Arn ]
              - "*"  
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - Fn::GetAtt: [ Bucket, Arn ]

custom:
  webpackIncludeModules: true

functions:
  api:
    handler: src/index.api
    environment:
      BUCKET:
        Ref: Bucket    
    events:
      - http:
          method: post
          path: graphql

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    WebDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: RedirectOrigin
              DomainName:
                Fn::Select: [2, Fn::Split: ["/", Fn::GetAtt: [Bucket, WebsiteURL]]]
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
          Enabled: true
          HttpVersion: http2
          DefaultCacheBehavior:
            ForwardedValues:
              QueryString: false
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: RedirectOrigin
            ViewerProtocolPolicy: allow-all
  Outputs:
    WebDistributionUrl:
      Description: "Cloudfront url"
      Value:
        Fn::GetAtt: WebDistribution.DomainName
